[SERVICE]
    Flush        1
    Log_Level    info
    Parsers_File parsers.conf

[INPUT]
    Name         forward
    Listen       0.0.0.0
    Port         24224

[FILTER]
    Name         parser
    Match        *
    Key_Name     log
    Parser       zerolog
    Reserve_Data on

[FILTER]
    Name   modify
    Match  *
    Remove container_id
    Remove container_name
    Remove source

[OUTPUT]
    Name                 opentelemetry
    Match                *
    Host                 otel-collector.prod.api.dotai.internal
    Port                 4318
    Logs_uri             /v1/logs
    Log_response_payload true
    Tls                  off
